#!/bin/bash
echo "🔧 Database Connection Fix Required"
echo ""
echo "The Supabase database connection is failing in production."
echo "Vercel needs the POOLED connection URL, not the direct one."
echo ""
echo "Update this environment variable in Vercel:"
echo ""
echo "DATABASE_URL=postgresql://postgres.vqlrvanvjbfkvyizfotj:JaYt2c4Qb1hQ2tsK@aws-0-us-east-2.pooler.supabase.com:5432/postgres"
echo ""
echo "Note: This uses 'pooler.supabase.com' instead of 'db.vqlr...' for better serverless performance"
echo ""
echo "Steps to fix:"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Find your 'rubric-challenge-xptp' project"
echo "3. Go to Settings → Environment Variables"
echo "4. Update DATABASE_URL with the POOLED URL above (note the different hostname)"
echo "5. Redeploy the application"
echo ""
echo "Then test with: curl https://rubric-challenge-xptp.vercel.app/api/test-db"
echo "" 